package com.fuyun.nursing.service.impl;

import com.baomidou.mybatisplus.core.toolkit.Wrappers;
import com.baomidou.mybatisplus.spring.service.impl.ServiceImpl;
import com.fuyun.common.context.OperatorContextHolder;
import com.fuyun.common.exception.BizException;
import com.fuyun.nursing.api.NursingErrorCode;
import com.fuyun.nursing.cache.NursingSeqGate;
import com.fuyun.nursing.dto.NursingRecordCreateRequest;
import com.fuyun.nursing.dto.NursingRecordReviseRequest;
import com.fuyun.nursing.entity.NursingRecord;
import com.fuyun.nursing.enums.RecordClass;
import com.fuyun.nursing.enums.RecordStatus;
import com.fuyun.nursing.mapper.NursingRecordMapper;
import com.fuyun.nursing.service.INursingRecordService;
import com.fuyun.nursing.service.IWardMetaService;
import com.fuyun.nursing.vo.NursingRecordVO;
import com.fuyun.nursing.vo.WardPatientDetailVO;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneId;
import java.util.List;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.transaction.annotation.Transactional;

/**
 * 护理记录单域服务实现（V802 nursing_record 业务面）。状态机（Spec :113）：create 落 DRAFT →
 * submit 经 @Update CAS 单语句锁定（DRAFT→SUBMITTED + 签名盖章，GC26 条件更新 + 影响行数判定）→
 * revise 仅对 SUBMITTED 插留痕新行（新号 + REVISED + revised_from，原行零改动保留——GC25
 * 修订留痕原值可见红线）；观察行归集 appendObservation 为 Task 5 体征域消费落点（正常合并当日
 * 观察行 / 异常独立落行）。patient_id/ward_id 一律经 IWardMetaService 在区行服务端装配（不信
 * 客户端）；record_time/signed_at 等文书业务时间一律服务器时间（GC25）。
 * 线程安全：无状态 singleton；写操作 @Transactional 收口。
 */
@Slf4j
public class NursingRecordServiceImpl extends ServiceImpl<NursingRecordMapper, NursingRecord>
        implements INursingRecordService {

    /** 移出/系统链路等无登录上下文场景的操作者回退值（与 V802 审计列默认同源） */
    private static final String SYSTEM_OPERATOR = "system";

    private final NursingSeqGate seqGate;

    private final IWardMetaService wardMetaService;

    /**
     * 全参构造器（装配归 NursingWebConfig @Import）。
     *
     * @param recordMapper 护理记录单 mapper，非空；ServiceImpl 基座 mapper
     * @param seqGate      护理业务号发号器，非空；NR 单号签发（Redis 原子自增）
     * @param wardMetaService 病区元数据服务，非空；在区校验与患者/病区归一（Task 3 面）
     */
    public NursingRecordServiceImpl(
            NursingRecordMapper recordMapper, NursingSeqGate seqGate, IWardMetaService wardMetaService) {
        this.seqGate = seqGate;
        this.wardMetaService = wardMetaService;
    }

    /**
     * 创建护理记录（草稿）：守卫链①在区校验（detail 查无在区行定性 NS-1004 患者不在区）→
     * ②记录类别格式校验（缺省 GENERAL，非法值 NS-1019）→ ③NursingSeqGate 取 NR 号 →
     * ④insert（status=DRAFT，record_time=服务器时间）。
     *
     * @param req 创建入参，非空；来源：操作者工作站表单
     * @return 记录行出参，非空
     * @throws BizException NS-1004（409 患者不在区）/ NS-1019（400 记录类别 code 非法）
     */
    @Override
    @Transactional
    public NursingRecordVO create(NursingRecordCreateRequest req) {
        // 守卫链①：在区校验（patient_id/ward_id 由在区行服务端装配，不信客户端）
        WardPatientDetailVO inWard = requireInWard(req.visitId());
        // 守卫链②：记录类别显式格式校验（缺省 GENERAL，与 appendObservation 病区默认同源）
        RecordClass recordClass =
                req.recordClass() == null ? RecordClass.GENERAL : RecordClass.fromCode(req.recordClass());
        if (recordClass == null) {
            throw new BizException(
                    NursingErrorCode.PARAM_FORMAT_INVALID, HttpStatus.BAD_REQUEST, "记录类别 code 非法：" + req.recordClass());
        }
        String operator = operator();
        NursingRecord row = new NursingRecord();
        row.setRecordNo(seqGate.nextNo("NR"));
        row.setVisitId(req.visitId());
        row.setPatientId(inWard.patientId());
        row.setWardId(inWard.wardId());
        row.setRecordClass(recordClass.getCode());
        // GC25 护理文书红线：记录时间一律服务器时间（不设入参组件）
        row.setRecordTime(OffsetDateTime.now());
        row.setObservation(req.observation());
        row.setMeasures(req.measures());
        row.setEvaluation(req.evaluation());
        row.setFreeText(req.freeText());
        row.setAutoGenerated(false);
        row.setStatus(RecordStatus.DRAFT.getCode());
        row.setCreatedBy(operator);
        row.setUpdatedBy(operator);
        // 数据库写操作：护理记录草稿落库（record_no 全局唯一由 uk_nursing_record_no 兜底）
        baseMapper.insert(row);
        log.info(
                "护理记录创建：recordNo={}，visitId={}，wardId={}，recordClass={}，operator={}",
                row.getRecordNo(),
                row.getVisitId(),
                row.getWardId(),
                row.getRecordClass(),
                operator);
        return NursingRecordVO.from(row);
    }

    /**
     * 按记录号回读单条护理记录（含修订链出参）。
     *
     * @param recordNo 护理记录号，非空；来源：路径参数
     * @return 记录行出参，非空
     * @throws BizException NS-1016（409 记录不存在）
     */
    @Override
    @Transactional(readOnly = true)
    public NursingRecordVO get(String recordNo) {
        return NursingRecordVO.from(requireByNo(recordNo));
    }

    /**
     * 按住院就诊号列护理记录（记录时间升序）；date 非空时收敛为服务器时区当日窗口
     * [当日 00:00, 次日 00:00)。
     *
     * @param visitId 住院就诊号，非空；来源：查询参数
     * @param date    记录日，可空（空=全部）；来源：查询参数
     * @return 记录出参清单（无行返回空清单，非 null）
     */
    @Override
    @Transactional(readOnly = true)
    public List<NursingRecordVO> listByVisit(String visitId, LocalDate date) {
        var wrapper = Wrappers.<NursingRecord>lambdaQuery().eq(NursingRecord::getVisitId, visitId);
        if (date != null) {
            // 当日窗口（服务器时区）：含头不含尾，record_time 为 TIMESTAMPTZ 边界安全
            wrapper.ge(NursingRecord::getRecordTime, dayStart(date))
                    .lt(NursingRecord::getRecordTime, dayStart(date.plusDays(1)));
        }
        wrapper.orderByAsc(NursingRecord::getRecordTime);
        // 数据库读操作：护理记录清单（记录时间升序；逻辑删由 @TableLogic 自动过滤）
        return baseMapper.selectList(wrapper).stream()
                .map(NursingRecordVO::from)
                .toList();
    }

    /**
     * 提交锁定（DRAFT→SUBMITTED）：@Update CAS 单语句（SET status/signed_operator/signed_at
     * WHERE status='DRAFT' AND deleted=0，GC26），0 行定性 NS-1007（不存在或已提交/已修订），
     * 并发重复提交由 CAS 行数判定兜底；成功后回读出参（携带签名留痕）。
     *
     * @param recordNo 护理记录号，非空；来源：路径参数
     * @return 提交后记录行出参，非空
     * @throws BizException NS-1007（409 记录不存在或已提交锁定）
     */
    @Override
    @Transactional
    public NursingRecordVO submit(String recordNo) {
        String operator = operator();
        // 数据库写操作：提交锁定 CAS（正文提交后锁定，GC25 红线；签名随 CAS 盖章）
        if (baseMapper.casSubmit(recordNo, operator) == 0) {
            throw new BizException(NursingErrorCode.RECORD_LOCKED, HttpStatus.CONFLICT, "护理记录不存在或已提交锁定：" + recordNo);
        }
        NursingRecord row = requireByNo(recordNo);
        log.info(
                "护理记录提交锁定：recordNo={}，visitId={}，signedOperator={}，signedAt={}",
                row.getRecordNo(),
                row.getVisitId(),
                row.getSignedOperator(),
                row.getSignedAt());
        return NursingRecordVO.from(row);
    }

    /**
     * 修订留痕（仅 SUBMITTED 可修订，否则 NS-1008）：插入修订新行（NursingSeqGate 新号 +
     * status=REVISED + revised_from=原号），继承原行归属（visit/patient/ward/类别）与关联引用；
     * 原行零改动保留——原值可见靠历史行不删（GC25 红线），修订件即生效件随签（signed_operator/
     * signed_at 承当前操作者与时点，时钟源与提交 CAS 同源 DB now()，消除签名链时序倒挂窗口）。
     *
     * @param recordNo 被修订的原记录号，非空；来源：路径参数
     * @param req      修订入参（整篇替换正文），非空；来源：操作者工作站表单
     * @return 修订件出参，非空
     * @throws BizException NS-1016（409 记录不存在）/ NS-1008（409 仅已提交记录可修订）
     */
    @Override
    @Transactional
    public NursingRecordVO revise(String recordNo, NursingRecordReviseRequest req) {
        // 守卫链①：原行定位 + 修订链合法性（仅 SUBMITTED 可发起修订；DRAFT/REVISED 均拒）
        NursingRecord original = requireByNo(recordNo);
        if (!RecordStatus.SUBMITTED.getCode().equals(original.getStatus())) {
            throw new BizException(
                    NursingErrorCode.RECORD_REVISE_NOT_ALLOWED,
                    HttpStatus.CONFLICT,
                    "仅已提交记录可发起修订：" + recordNo + "，当前状态=" + original.getStatus());
        }
        String operator = operator();
        // 文书业务时间统一时钟源：与提交 CAS 内 now() 同源取 DB 时刻（record_time/signed_at 同一值）
        OffsetDateTime dbNow = baseMapper.dbNow();
        NursingRecord revised = new NursingRecord();
        revised.setRecordNo(seqGate.nextNo("NR"));
        revised.setVisitId(original.getVisitId());
        revised.setPatientId(original.getPatientId());
        revised.setWardId(original.getWardId());
        revised.setRecordClass(original.getRecordClass());
        revised.setRecordTime(dbNow);
        revised.setObservation(req.observation());
        revised.setMeasures(req.measures());
        revised.setEvaluation(req.evaluation());
        revised.setFreeText(req.freeText());
        revised.setRefVitalId(original.getRefVitalId());
        revised.setRefEventRef(original.getRefEventRef());
        revised.setAutoGenerated(false);
        revised.setSignedOperator(operator);
        revised.setSignedAt(dbNow);
        revised.setStatus(RecordStatus.REVISED.getCode());
        revised.setRevisedFrom(recordNo);
        revised.setCreatedBy(operator);
        revised.setUpdatedBy(operator);
        // 数据库写操作：修订件落库；原行零改动（无任何 UPDATE 触达原行，原值可见靠历史行）
        baseMapper.insert(revised);
        log.info(
                "护理记录修订留痕：原recordNo={}，新recordNo={}，visitId={}，operator={}",
                recordNo,
                revised.getRecordNo(),
                revised.getVisitId(),
                operator);
        return NursingRecordVO.from(revised);
    }

    /**
     * 观察行归集落点（Task 5 体征域消费）：abnormal=false 且当日已有 autoGenerated=true 观察行 →
     * @Update 条件更新换行追加（GC26）；abnormal=true 或当日无观察行 → insert 新行
     * （autoGenerated=true、record_class=GENERAL 病区默认、record_time=服务器时间）。
     * 合并谓词以 abnormal_flag=false 限定正常行（GC19：异常行不被正常内容稀释；同日正常行+
     * 异行并存时单行命中不抛 TooManyResults）；条件更新 0 行（行被并发删改，GC26）同样落入
     * 新建分支，归集内容绝不静默丢失。
     *
     * @param visitId    住院就诊号，非空；来源：体征记录链
     * @param content    归集观察内容，非空；来源：体征域拼装（正常摘要/异常项描述）
     * @param abnormal   是否含异常项（true=独立落行，false=合并当日正常行）
     * @param recorderId 记录人业务标识，非空；来源：体征记录操作者
     * @throws BizException NS-1004（409 患者不在区）
     */
    @Override
    @Transactional
    public void appendObservation(String visitId, String content, boolean abnormal, String recorderId) {
        // 在区校验兜底（Task 5 体征链已校验，此处保 patient_id/ward_id 非空列有权威来源）
        WardPatientDetailVO inWard = requireInWard(visitId);
        String operator = recorderId == null || recorderId.isBlank() ? operator() : recorderId;
        if (!abnormal) {
            // 合并分支：定位当日（服务器时区）自动归集的正常观察行（abnormal_flag=false 限定）
            NursingRecord existing = baseMapper.selectOne(Wrappers.<NursingRecord>lambdaQuery()
                    .eq(NursingRecord::getVisitId, visitId)
                    .eq(NursingRecord::getAutoGenerated, true)
                    .eq(NursingRecord::getAbnormalFlag, false)
                    .ge(NursingRecord::getRecordTime, dayStart(LocalDate.now()))
                    .lt(NursingRecord::getRecordTime, dayStart(LocalDate.now().plusDays(1))));
            // 数据库写操作：条件更新换行追加（COALESCE 兜底历史行 observation 为 NULL）；GC26
            // 影响行数判定——0 行（行已被并发删改）与未命中同样落入新建分支，不静默丢失
            if (existing != null && baseMapper.appendObservation(existing.getId(), content, operator) > 0) {
                log.info("观察行归集合并：visitId={}，recordNo={}，operator={}", visitId, existing.getRecordNo(), operator);
                return;
            }
        }
        // 新建分支：异常项独立落行（当日无正常观察行或合并 0 行时正常内容也落独立行）
        NursingRecord row = new NursingRecord();
        row.setRecordNo(seqGate.nextNo("NR"));
        row.setVisitId(visitId);
        row.setPatientId(inWard.patientId());
        row.setWardId(inWard.wardId());
        row.setRecordClass(RecordClass.GENERAL.getCode());
        row.setRecordTime(OffsetDateTime.now());
        row.setObservation(content);
        row.setAutoGenerated(true);
        // 异常行置 abnormal_flag=true（正常归集合并谓词不再命中，GC19 异常不被稀释）
        row.setAbnormalFlag(abnormal);
        row.setStatus(RecordStatus.DRAFT.getCode());
        row.setCreatedBy(operator);
        row.setUpdatedBy(operator);
        // 数据库写操作：自动观察行落库（异常独立成行，保证异常项不被当日正常行稀释）
        baseMapper.insert(row);
        log.info(
                "观察行归集新建：recordNo={}，visitId={}，abnormal={}，operator={}",
                row.getRecordNo(),
                visitId,
                abnormal,
                operator);
    }

    /** 按 visit_id 校验在区（IWardMetaService detail；查无在区行定性 NS-1004 患者不在区）。 */
    private WardPatientDetailVO requireInWard(String visitId) {
        try {
            return wardMetaService.detail(visitId);
        } catch (BizException e) {
            // 在区行不存在（detail 定性 NS-1001）→ 文书域语境转 NS-1004 患者不在区
            if (NursingErrorCode.WARD_PATIENT_NOT_FOUND.equals(e.getErrorCode())) {
                throw new BizException(
                        NursingErrorCode.PATIENT_BLOCKED, HttpStatus.CONFLICT, "患者不在区，禁止文书操作：visitId=" + visitId);
            }
            throw e;
        }
    }

    /** 按记录号定位护理记录行（逻辑删由 @TableLogic 自动过滤；未命中定性 NS-1016）。 */
    private NursingRecord requireByNo(String recordNo) {
        NursingRecord row =
                baseMapper.selectOne(Wrappers.<NursingRecord>lambdaQuery().eq(NursingRecord::getRecordNo, recordNo));
        if (row == null) {
            throw new BizException(NursingErrorCode.CONFLICT, HttpStatus.CONFLICT, "护理记录不存在：" + recordNo);
        }
        return row;
    }

    /** 服务器时区当日零点（当日窗口含头边界）。 */
    private OffsetDateTime dayStart(LocalDate date) {
        return date.atStartOfDay(ZoneId.systemDefault()).toOffsetDateTime();
    }

    /** 操作者取值（免登录上下文回退 system，与审计列默认同源）。 */
    private String operator() {
        String operator = OperatorContextHolder.get();
        return operator == null || operator.isBlank() ? SYSTEM_OPERATOR : operator;
    }
}
