package com.fuyun.nursing.service;

import com.fuyun.nursing.dto.NursingRecordCreateRequest;
import com.fuyun.nursing.dto.NursingRecordReviseRequest;
import com.fuyun.nursing.vo.NursingRecordVO;
import java.time.LocalDate;
import java.util.List;

/**
 * 护理记录单域服务（V802 nursing_record 业务面；Task 5 消费 appendObservation 冻结面）。
 * 状态机（Spec :113）：DRAFT →（submit CAS）→ SUBMITTED →（revise 插新行）→ REVISED；
 * 提交后锁定（NS-1007）、修订留痕原值可见（新行 REVISED + revised_from，原行保留不删——
 * GC25 护理文书红线）；文书业务时间一律服务器时间。
 *
 * <p>线程安全：无状态 singleton；写操作 @Transactional 收口（实现侧）。
 */
public interface INursingRecordService {

    /**
     * 创建护理记录（草稿）：在区校验（查无 → NS-1004）→ NursingSeqGate 取号（NR 前缀）→
     * insert（status=DRAFT，record_time=服务器时间）；记录类别缺省 GENERAL，非法值 NS-1019。
     *
     * @param req 创建入参，非空；来源：操作者工作站表单
     * @return 记录行出参，非空
     * @throws BizException NS-1004（409 患者不在区）/ NS-1019（400 记录类别 code 非法）
     */
    NursingRecordVO create(NursingRecordCreateRequest req);

    /**
     * 按记录号回读单条护理记录（含修订链出参）。
     *
     * @param recordNo 护理记录号，非空；来源：路径参数
     * @return 记录行出参，非空
     * @throws BizException NS-1016（409 记录不存在）
     */
    NursingRecordVO get(String recordNo);

    /**
     * 按住院就诊号列护理记录（按记录时间升序）；date 非空时仅取该日（服务器时区当日窗口）。
     *
     * @param visitId 住院就诊号，非空；来源：查询参数
     * @param date    记录日（yyyy-MM-dd 语义），可空（空=全部）；来源：查询参数
     * @return 记录出参清单（无行返回空清单，非 null）；按记录时间升序
     */
    List<NursingRecordVO> listByVisit(String visitId, LocalDate date);

    /**
     * 提交锁定（DRAFT→SUBMITTED）：@Update CAS + 影响行数判定（GC26），0 行定性 NS-1007
     * （不存在或已提交锁定）；签名操作者/签名时间随 CAS 盖章。
     *
     * @param recordNo 护理记录号，非空；来源：路径参数
     * @return 提交后记录行出参，非空
     * @throws BizException NS-1007（409 记录不存在或已提交锁定）
     */
    NursingRecordVO submit(String recordNo);

    /**
     * 修订留痕（仅 SUBMITTED 可修订，否则 NS-1008）：插入修订新行（新号 + status=REVISED +
     * revised_from=原号），原行零改动保留（原值可见）；修订件继承原行归属与引用。
     *
     * @param recordNo 被修订的原记录号，非空；来源：路径参数
     * @param req      修订入参（整篇替换正文），非空；来源：操作者工作站表单
     * @return 修订件出参，非空
     * @throws BizException NS-1016（409 记录不存在）/ NS-1008（409 仅已提交记录可修订）
     */
    NursingRecordVO revise(String recordNo, NursingRecordReviseRequest req);

    /**
     * 观察行归集落点（Task 5 体征域消费冻结面）：abnormal=false 合并当日既有自动观察行
     * （@Update 条件更新换行追加）；abnormal=true 或当日无观察行时 insert 新行
     * （autoGenerated=true、record_class=GENERAL 病区默认）。
     *
     * @param visitId    住院就诊号，非空；来源：体征记录链
     * @param content    归集观察内容（体征摘要/异常项描述），非空；来源：体征域拼装
     * @param abnormal   是否含异常项（true=独立落行，false=合并当日正常行）
     * @param recorderId 记录人业务标识，非空；来源：体征记录操作者
     * @throws BizException NS-1004（409 患者不在区）
     */
    void appendObservation(String visitId, String content, boolean abnormal, String recorderId);
}
