package com.fuyun.nursing.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import java.time.OffsetDateTime;
import lombok.Getter;
import lombok.Setter;

/**
 * 护理记录单实体（nursing.nursing_record，V802）：一般/病重病危表格式护理记录（病历要件，
 * 随病历长期保存）。提交锁定 + 修订留痕原值可见（GC25 红线）：SUBMITTED 后正文锁定；
 * 修订产生新行（status=REVISED、revised_from=原号），原行保持 SUBMITTED 不删——原值可见
 * 靠历史行承载。签名引用 P2 接 M01 CA，P1 有效留痕=signed_operator + signed_at。
 */
@Getter
@Setter
@TableName("nursing.nursing_record")
public class NursingRecord {

    /** 雪花主键（MP ASSIGN_ID） */
    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /** 护理记录号（NR+yyyyMMdd+5 位流水，本模块 NursingSeqGate 签发，全局唯一） */
    private String recordNo;

    /** 住院就诊号（I 型 14 位；在区校验经 IWardMetaService） */
    private String visitId;

    /** 患者主索引（在区行归一后服务端装配，不信客户端） */
    private Long patientId;

    /** 病区编码（在区行归一后服务端装配） */
    private String wardId;

    /** 记录类别（RecordClass code：GENERAL 一般 / CRITICAL 病重病危） */
    private String recordClass;

    /** 记录时间（服务器时间，GC25 护理文书红线） */
    private OffsetDateTime recordTime;

    /** 病情观察（结构化段；自动归集观察行经 appendObservation 追加） */
    private String observation;

    /** 护理措施（结构化段） */
    private String measures;

    /** 效果评价（结构化段） */
    private String evaluation;

    /** 自由文本补充 */
    private String freeText;

    /** 关联体征记录引用（Task 5 体征域回填） */
    private Long refVitalId;

    /** 关联特殊事件引用（type_key） */
    private String refEventRef;

    /** 是否由体征归集自动生成（观察行；true 时当日正常内容合并、异常独立落行） */
    private Boolean autoGenerated;

    /** 电子签名引用（M01 CA，P2 接；P1 留空） */
    private String signatureRef;

    /** 签名操作者（P1 有效留痕；submit 时随 CAS 盖章） */
    private String signedOperator;

    /** 签名时间（submit 时随 CAS 由 DB now() 盖章） */
    private OffsetDateTime signedAt;

    /** 记录状态（RecordStatus code：DRAFT / SUBMITTED / REVISED） */
    private String status;

    /** 修订链：被修订的原记录号（修订件指向原号，原行保留保证原值可见） */
    private String revisedFrom;

    /** 创建时刻 */
    private OffsetDateTime createdAt;

    /** 更新时刻 */
    private OffsetDateTime updatedAt;

    /** 创建者 */
    private String createdBy;

    /** 更新者 */
    private String updatedBy;

    /** 逻辑删标记 */
    @TableLogic
    private Integer deleted;
}
