/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/patient/privacy-mask-rules/{ruleCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/patients/{patientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/iotda-fallback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestIotdaFallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/practice/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["check"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/dict-versions/{versionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/dict-versions/{versionId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/dict-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/dict-types/{typeCode}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/privacy/unmask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unmask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/privacy-auths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auths"];
        put?: never;
        post: operations["createAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/possible-duplicates/{id}/exclude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exclude"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/patients/{patientId}/unfreeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unfreeze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/patients/{patientId}/identifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["attach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/patients/{patientId}/health-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addItem_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/patients/{patientId}/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["freeze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/patients/match-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["matchCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/merges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/merges/{id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["split"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/merges/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/identifiers/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/health-items/{id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["correct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/cards/unbind/{cardNo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unbind"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/cards/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/cards/loss/{cardNo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loss"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/cards/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/cards/bind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bind"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/card-accounts/{id}/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["freeze_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/card-accounts/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/mdm-subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/dead-letters/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/dead-letters/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["close_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/dicts/{typeCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/privacy-mask-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["maskRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/privacy-access-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accessLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/possible-duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/patients/{patientId}/health-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/patients/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/cards/{cardNo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/card-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/card-accounts/{id}/txns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["txns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/received-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/event-registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/event-publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/dead-letters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/mdm-subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["unregister"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PrivacyMaskRuleUpdateRequest: {
            maskPattern?: string;
            exemptRoles?: string;
            enabled?: boolean;
        };
        PrivacyMaskRuleVO: {
            ruleCode?: string;
            targetField?: string;
            maskPattern?: string;
            exemptRoles?: string[];
            enabled?: boolean;
        };
        PatientUpdateRequest: {
            name?: string;
            sex?: string;
            birthDate?: string;
            ethnicity?: string;
            maritalStatus?: string;
            occupation?: string;
            bloodType?: string;
            mobile?: string;
            address?: string;
        };
        FallbackIngestRequest: {
            deviceId: string;
            metricCode: string;
            value: string;
            unit?: string;
            /** Format: date-time */
            occurredAt: string;
            quality?: string;
        };
        FallbackIngestResponse: {
            accepted?: boolean;
        };
        PracticeCheckRequest: {
            /** @example 0 */
            employeeId: string;
            grantType: string;
            /** Format: date-time */
            checkTime?: string;
        };
        PracticeCheckResponse: {
            employeeId?: string;
            grantType?: string;
            /** Format: date-time */
            checkTime?: string;
            passed?: boolean;
            reason?: string;
        };
        DictItemCreateRequest: {
            itemCode: string;
            itemName: string;
            parentCode?: string;
            /** Format: int32 */
            sort?: number;
        };
        DictItemVO: {
            itemCode?: string;
            itemName?: string;
            parentCode?: string;
            /** Format: int32 */
            sort?: number;
        };
        DictTypeCreateRequest: {
            typeCode: string;
            typeName: string;
            nationalStandard?: boolean;
            remark?: string;
        };
        DictTypeVO: {
            /** @example 0 */
            id?: string;
            typeCode?: string;
            typeName?: string;
            nationalStandard?: boolean;
            remark?: string;
        };
        DictVersionVO: {
            typeCode?: string;
            /** Format: int32 */
            version?: number;
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED" | "DEPRECATED";
            /** Format: date-time */
            publishedAt?: string;
            items?: components["schemas"]["DictItemVO"][];
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LoginResponse: {
            accessToken?: string;
            refreshToken?: string;
            tokenType?: string;
            /** @example 0 */
            expiresIn?: string;
            user?: components["schemas"]["UserVO"];
        };
        UserVO: {
            /** @example 0 */
            userId?: string;
            loginName?: string;
            displayName?: string;
            /** @example 0 */
            orgId?: string;
            roles?: string[];
        };
        LoginRequest: {
            loginName: string;
            password: string;
        };
        UnmaskRequest: {
            /** @example 0 */
            patientId: string;
            fields: string[];
            purpose: string;
        };
        UnmaskVO: {
            /** @example 0 */
            patientId?: string;
            values?: {
                [key: string]: string;
            };
        };
        PrivacyAuthCreateRequest: {
            /** @example 0 */
            patientId: string;
            authType: string;
            authBasis: string;
            scope?: string;
            signedAtIso?: string;
            validToIso?: string;
        };
        PrivacyAuthVO: {
            /** @example 0 */
            id?: string;
            /** @example 0 */
            patientId?: string;
            authType?: string;
            authBasis?: string;
            scope?: string;
            /** Format: date-time */
            signedAt?: string;
            /** Format: date-time */
            validTo?: string;
            derivedStatus?: string;
        };
        ExcludeRequest: {
            note: string;
        };
        PatientCreateRequest: {
            name: string;
            sex: string;
            birthDate?: string;
            ethnicity?: string;
            maritalStatus?: string;
            occupation?: string;
            bloodType?: string;
            idCardNo?: string;
            mobile?: string;
            address?: string;
            registerChannel: string;
            archiveSource?: string;
            identifierType?: string;
            identifierValue?: string;
            cardNo?: string;
            informedConsentRef: string;
        };
        PatientMatchCheckVO: {
            outcome?: string;
            /** @example 0 */
            candidatePatientId?: string;
            score?: number;
            matchedRules?: string[];
        };
        IdentifierCreateRequest: {
            identifierType: string;
            identifierValue: string;
            cardNo?: string;
        };
        IdentifierVO: {
            /** @example 0 */
            id?: string;
            identifierType?: string;
            cardNo?: string;
            status?: string;
            isPrimary?: boolean;
            /** Format: date-time */
            boundAt?: string;
            /** Format: date-time */
            unboundAt?: string;
        };
        HealthItemCreateRequest: {
            itemType: string;
            itemCode?: string;
            itemName: string;
            severity?: string;
            onsetDate?: string;
            source: string;
            note?: string;
        };
        HealthItemVO: {
            /** @example 0 */
            id?: string;
            itemType?: string;
            itemCode?: string;
            itemName?: string;
            severity?: string;
            /** Format: date */
            onsetDate?: string;
            status?: string;
            source?: string;
            note?: string;
            /** @example 0 */
            correctOfItemId?: string;
        };
        FreezeRequest: {
            reason: string;
        };
        PatientMatchCheckRequest: {
            name: string;
            sex: string;
            birthDate?: string;
            idCardNo?: string;
            mobile?: string;
        };
        MergeCreateRequest: {
            /** @example 0 */
            survivorPatientId: string;
            /** @example 0 */
            mergedPatientId: string;
            mergeReason: string;
            /** @example 0 */
            possibleDuplicateId?: string;
        };
        MergeRecordVO: {
            /** @example 0 */
            id?: string;
            /** @example 0 */
            survivorPatientId?: string;
            /** @example 0 */
            mergedPatientId?: string;
            mergeReason?: string;
            status?: string;
            operator?: string;
            approvedBy?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            reversedAt?: string;
            reverseReason?: string;
        };
        ResolveRequest: {
            identifierType: string;
            identifierValue: string;
        };
        ResolveVO: {
            /** @example 0 */
            patientId?: string;
            /** @example 0 */
            resolvedPatientId?: string;
            status?: string;
            blocked?: boolean;
            blockReason?: string;
        };
        HealthItemCorrectRequest: {
            itemName: string;
            itemCode?: string;
            severity?: string;
            onsetDate?: string;
            note: string;
        };
        CardReplaceRequest: {
            cardNo: string;
            newCardNo: string;
        };
        CardVO: {
            /** @example 0 */
            identifierId?: string;
            /** @example 0 */
            patientId?: string;
            cardNo?: string;
            status?: string;
            /** Format: date-time */
            boundAt?: string;
            /** Format: date-time */
            unboundAt?: string;
        };
        CardIssueRequest: {
            /** @example 0 */
            patientId: string;
            cardNo: string;
        };
        CardBindRequest: {
            cardNo: string;
            /** @example 0 */
            patientId: string;
        };
        MdmSubscriptionCreateRequest: {
            topic: string;
            subscriberModule: string;
            syncMode: string;
        };
        MdmSubscriptionVO: {
            /** @example 0 */
            id?: string;
            topic?: string;
            subscriberModule?: string;
            syncMode?: string;
            /** @example 0 */
            lastVersion?: string;
            /** Format: date-time */
            lastSyncAt?: string;
            /** Format: date-time */
            lastReconAt?: string;
            reconStatus?: string;
        };
        DeadLetterDetailVO: {
            /** @example 0 */
            id?: string;
            sourceQueue?: string;
            routingKey?: string;
            eventType?: string;
            eventId?: string;
            payloadBody?: string;
            payloadDigest?: string;
            failReason?: string;
            /** Format: date-time */
            firstDeadAt?: string;
            status?: string;
            /** Format: int32 */
            replayCount?: number;
            handler?: string;
            handleNote?: string;
            /** Format: date-time */
            handledAt?: string;
        };
        DeadLetterCloseRequest: {
            handleNote: string;
        };
        PageResultPrivacyAccessLogVO: {
            content?: components["schemas"]["PrivacyAccessLogVO"][];
            /** @example 0 */
            page?: string;
            /** @example 0 */
            size?: string;
            /** @example 0 */
            total?: string;
        };
        PrivacyAccessLogVO: {
            /** @example 0 */
            id?: string;
            operatorId?: string;
            /** @example 0 */
            patientId?: string;
            accessType?: string;
            purpose?: string;
            fields?: string;
            /** Format: date-time */
            occurredAt?: string;
            traceId?: string;
        };
        PageResultPossibleDuplicateVO: {
            content?: components["schemas"]["PossibleDuplicateVO"][];
            /** @example 0 */
            page?: string;
            /** @example 0 */
            size?: string;
            /** @example 0 */
            total?: string;
        };
        PossibleDuplicateVO: {
            /** @example 0 */
            id?: string;
            /** @example 0 */
            patientIdA?: string;
            /** @example 0 */
            patientIdB?: string;
            matchScore?: number;
            matchedRules?: string[];
            source?: string;
            status?: string;
            reviewedBy?: string;
            /** Format: date-time */
            reviewedAt?: string;
            reviewNote?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PatientVO: {
            /** @example 0 */
            patientId?: string;
            name?: string;
            sex?: string;
            /** Format: date */
            birthDate?: string;
            idCardNo?: string;
            mobile?: string;
            address?: string;
            status?: string;
            /** @example 0 */
            mergedIntoPatientId?: string;
            realNameFlag?: boolean;
            registerChannel?: string;
            archiveSource?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        HealthSummaryVO: {
            /** @example 0 */
            patientId?: string;
            bloodType?: string;
            rhType?: string;
            pastHistory?: string;
            familyHistory?: string;
            /** Format: date-time */
            summaryUpdatedAt?: string;
            items?: components["schemas"]["HealthItemVO"][];
        };
        PageResultPatientVO: {
            content?: components["schemas"]["PatientVO"][];
            /** @example 0 */
            page?: string;
            /** @example 0 */
            size?: string;
            /** @example 0 */
            total?: string;
        };
        CardAccountVO: {
            /** @example 0 */
            id?: string;
            /** @example 0 */
            patientId?: string;
            /** @example 0 */
            balance?: string;
            status?: string;
            /** Format: date-time */
            openedAt?: string;
            /** Format: date-time */
            closedAt?: string;
        };
        CardTxnVO: {
            /** @example 0 */
            id?: string;
            txnType?: string;
            /** @example 0 */
            amount?: string;
            /** @example 0 */
            balanceAfter?: string;
            bizRef?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        PageResultCardTxnVO: {
            content?: components["schemas"]["CardTxnVO"][];
            /** @example 0 */
            page?: string;
            /** @example 0 */
            size?: string;
            /** @example 0 */
            total?: string;
        };
        PageResultReceivedEventVO: {
            content?: components["schemas"]["ReceivedEventVO"][];
            /** @example 0 */
            page?: string;
            /** @example 0 */
            size?: string;
            /** @example 0 */
            total?: string;
        };
        ReceivedEventVO: {
            /** @example 0 */
            id?: string;
            /** Format: uuid */
            eventId?: string;
            eventType?: string;
            producer?: string;
            /** Format: date-time */
            occurredAt?: string;
            consumerModule?: string;
            status?: string;
            failReason?: string;
            /** Format: int32 */
            retryCount?: number;
            /** Format: date-time */
            receivedAt?: string;
            /** Format: date-time */
            processedAt?: string;
        };
        PageResultMdmSubscriptionVO: {
            content?: components["schemas"]["MdmSubscriptionVO"][];
            /** @example 0 */
            page?: string;
            /** @example 0 */
            size?: string;
            /** @example 0 */
            total?: string;
        };
        EventRegistryVO: {
            /** @example 0 */
            id?: string;
            eventType?: string;
            producerModule?: string;
            payloadDesc?: string;
            subscriberModules?: string;
            status?: string;
            /** Format: date-time */
            registeredAt?: string;
        };
        PageResultEventRegistryVO: {
            content?: components["schemas"]["EventRegistryVO"][];
            /** @example 0 */
            page?: string;
            /** @example 0 */
            size?: string;
            /** @example 0 */
            total?: string;
        };
        EventPublicationVO: {
            /** Format: uuid */
            id?: string;
            listenerId?: string;
            eventType?: string;
            /** Format: date-time */
            publicationDate?: string;
            /** Format: date-time */
            completionDate?: string;
            status?: string;
        };
        PageResultEventPublicationVO: {
            content?: components["schemas"]["EventPublicationVO"][];
            /** @example 0 */
            page?: string;
            /** @example 0 */
            size?: string;
            /** @example 0 */
            total?: string;
        };
        DeadLetterVO: {
            /** @example 0 */
            id?: string;
            sourceQueue?: string;
            routingKey?: string;
            eventType?: string;
            eventId?: string;
            payloadDigest?: string;
            payloadPreview?: string;
            failReason?: string;
            /** Format: date-time */
            firstDeadAt?: string;
            status?: string;
            /** Format: int32 */
            replayCount?: number;
            handler?: string;
            handleNote?: string;
            /** Format: date-time */
            handledAt?: string;
        };
        PageResultDeadLetterVO: {
            content?: components["schemas"]["DeadLetterVO"][];
            /** @example 0 */
            page?: string;
            /** @example 0 */
            size?: string;
            /** @example 0 */
            total?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleCode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivacyMaskRuleUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrivacyMaskRuleVO"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PatientVO"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    ingestIotdaFallback: {
        parameters: {
            query?: never;
            header?: {
                "X-Iot-Fallback-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FallbackIngestRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FallbackIngestResponse"];
                };
            };
        };
    };
    check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeCheckRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PracticeCheckResponse"];
                };
            };
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictItemCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DictItemVO"];
                };
            };
        };
    };
    createType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictTypeCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DictTypeVO"];
                };
            };
        };
    };
    createVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DictVersionVO"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    unmask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnmaskRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UnmaskVO"];
                };
            };
        };
    };
    auths: {
        parameters: {
            query: {
                patientId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrivacyAuthVO"][];
                };
            };
        };
    };
    createAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivacyAuthCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrivacyAuthVO"];
                };
            };
        };
    };
    exclude: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExcludeRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PatientMatchCheckVO"];
                };
            };
        };
    };
    unfreeze: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IdentifierVO"][];
                };
            };
        };
    };
    attach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentifierCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IdentifierVO"];
                };
            };
        };
    };
    addItem_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthItemCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthItemVO"];
                };
            };
        };
    };
    freeze: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FreezeRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    matchCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientMatchCheckRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PatientMatchCheckVO"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MergeRecordVO"];
                };
            };
        };
    };
    split: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MergeRecordVO"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MergeRecordVO"];
                };
            };
        };
    };
    resolve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResolveVO"];
                };
            };
        };
    };
    correct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthItemCorrectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthItemVO"];
                };
            };
        };
    };
    unbind: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardNo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardReplaceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CardVO"];
                };
            };
        };
    };
    loss: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardNo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardIssueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CardVO"];
                };
            };
        };
    };
    bind: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardBindRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CardVO"];
                };
            };
        };
    };
    freeze_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                topic?: string;
                subscriberModule?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResultMdmSubscriptionVO"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MdmSubscriptionCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MdmSubscriptionVO"];
                };
            };
        };
    };
    replay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeadLetterDetailVO"];
                };
            };
        };
    };
    close_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeadLetterCloseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeadLetterDetailVO"];
                };
            };
        };
    };
    readVersion: {
        parameters: {
            query?: {
                version?: number;
            };
            header?: never;
            path: {
                typeCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DictVersionVO"];
                };
            };
        };
    };
    maskRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrivacyMaskRuleVO"][];
                };
            };
        };
    };
    accessLogs: {
        parameters: {
            query?: {
                patientId?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResultPrivacyAccessLogVO"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                status?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResultPossibleDuplicateVO"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthSummaryVO"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                keyword?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResultPatientVO"];
                };
            };
        };
    };
    detail_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardNo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CardVO"];
                };
            };
        };
    };
    detail_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CardAccountVO"];
                };
            };
        };
    };
    txns: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResultCardTxnVO"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                eventType?: string;
                eventId?: string;
                consumerModule?: string;
                status?: string;
                receivedFrom?: string;
                receivedTo?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResultReceivedEventVO"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                eventType?: string;
                producerModule?: string;
                status?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResultEventRegistryVO"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: {
                eventType?: string;
                status?: string;
                publishedFrom?: string;
                publishedTo?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResultEventPublicationVO"];
                };
            };
        };
    };
    list_6: {
        parameters: {
            query?: {
                status?: string;
                eventType?: string;
                eventId?: string;
                sourceQueue?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResultDeadLetterVO"];
                };
            };
        };
    };
    detail_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeadLetterDetailVO"];
                };
            };
        };
    };
    unregister: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
