package com.fuyun.nursing.vo;

import com.fuyun.nursing.entity.NursingRecord;
import java.time.OffsetDateTime;

/**
 * 护理记录单出参（创建/查询/提交/修订共用回读面）。修订链经 revisedFrom 表达：原行保留
 * SUBMITTED（原值可见），修订件携 revisedFrom=原号（GC25 留痕红线）。
 *
 * @param recordNo      护理记录号（NR+yyyyMMdd+5 位流水）
 * @param visitId       住院就诊号
 * @param patientId     患者主索引
 * @param wardId        病区编码
 * @param recordClass   记录类别（RecordClass code）
 * @param recordTime    记录时间（服务器时间）
 * @param observation   病情观察（结构化段）
 * @param measures      护理措施（结构化段）
 * @param evaluation    效果评价（结构化段）
 * @param freeText      自由文本补充
 * @param autoGenerated 是否体征归集自动生成的观察行
 * @param signedOperator 签名操作者（P1 有效留痕；未提交为 null）
 * @param signedAt      签名时间（未提交为 null）
 * @param status        记录状态（RecordStatus code：DRAFT/SUBMITTED/REVISED）
 * @param revisedFrom   被修订的原记录号（仅修订件有值）
 */
public record NursingRecordVO(
        String recordNo,
        String visitId,
        Long patientId,
        String wardId,
        String recordClass,
        OffsetDateTime recordTime,
        String observation,
        String measures,
        String evaluation,
        String freeText,
        Boolean autoGenerated,
        String signedOperator,
        OffsetDateTime signedAt,
        String status,
        String revisedFrom) {

    /**
     * 实体→出参静态工厂（关键业务字段手写映射，禁 MapStruct——backend 宪法 A.1-8 先例）。
     *
     * @param entity 护理记录行，非空
     * @return 护理记录出参，非空
     */
    public static NursingRecordVO from(NursingRecord entity) {
        return new NursingRecordVO(
                entity.getRecordNo(),
                entity.getVisitId(),
                entity.getPatientId(),
                entity.getWardId(),
                entity.getRecordClass(),
                entity.getRecordTime(),
                entity.getObservation(),
                entity.getMeasures(),
                entity.getEvaluation(),
                entity.getFreeText(),
                entity.getAutoGenerated(),
                entity.getSignedOperator(),
                entity.getSignedAt(),
                entity.getStatus(),
                entity.getRevisedFrom());
    }
}
